export const productsData = [
  {
    id: "p-01",
    initialPrice: 800000,
    title: "Bộ bát đĩa sứ 16 món Wickham",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "kitchen-appliances",
    distributor: { name: "Phố Xinh", search: "pho-xinh" },
    tags: {
      new: false,
      bestSeller: true,
      discount: 20,
      freeShip: false,
      gift: false,
    },
    promotion: [
      {
        type: "freeShip-on-total",
        promotionCode: "PhoXinhFreeShip",
        totalRate: "1,5 triệu",
      },
    ],
    sort: [
      {
        type: "color",
        defaultValue: "white",
        name: "Màu sắc",
        values: [
          { value: "white", name: "Trắng", default: true },
          { value: "pink", name: "Hồng" },
        ],
      },
    ],
    policy: [{ deliveryDate: { from: 3, to: 5 }, icon: "delivery" }],
    specs: {
      size: null,
      madeIn: "Việt Nam",
      material: ["Sứ"],
      belongings: null,
    },
  },
  {
    id: "p-02",
    initialPrice: 5500000,
    title: "Bàn ăn tròn chân gỗ hạt dẻ",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "table",
    distributor: { name: "Chilai", search: "chilai" },
    tags: {
      new: true,
      bestSeller: false,
      discount: false,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "ChilaiFreeShip",
      },
    ],
    sort: [],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: `39'' L x 39'' D x 30'' H`,
      madeIn: "Việt Nam",
      material: ["Sứ", "Thủy tinh"],
      belongings: null,
    },
  },
  {
    id: "p-03",
    initialPrice: 2600000,
    title: "Bàn cà phê kèm ngăn để đồ Alviva",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "table",
    distributor: { name: "Hòa Phát", search: "hoa-phat" },
    tags: {
      new: false,
      bestSeller: false,
      discount: 20,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "17'' H x 38'' L x 18'' D",
      madeIn: "Việt Nam",
      material: ["Nhôm"],
      belongings: null,
    },
  },
  {
    id: "p-04",
    initialPrice: 3600000,
    title: "Bộ giường Newt Low",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "bed",
    distributor: { name: "Decox", search: "decox" },
    tags: {
      new: false,
      bestSeller: true,
      discount: 15,
      freeShip: false,
      gift: true,
    },
    promotion: [
      {
        type: "freeShip-on-total",
        promotionCode: "DECOXFreeShip",
        totalRate: "4 triệu",
      },
      {
        gifts: ["Bộ vỏ gối, ga trải giường Newt Low"],
      },
    ],
    sort: [],
    policy: [
      { warranty: { time: 2, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: true, icon: "gift" },
    ],
    specs: {
      size: "53.5'' W x 74.70'' L",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: "Bộ khung đỡ",
    },
  },
  {
    id: "p-05",
    initialPrice: 7000000,
    title: "Ghế sofa Loveseat Cutshall",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "chair",
    distributor: { name: "Chilai", search: "chilai" },
    tags: {
      new: true,
      bestSeller: false,
      discount: 10,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "ChilaiFreeShip",
      },
    ],
    sort: [
      {
        type: "color",
        defaultValue: "blue",
        name: "Màu sắc",
        values: [
          { value: "blue", name: "Xanh dương", default: true },
          { value: "mustard", name: "Vàng nghệ" },
          { value: "moon-light", name: "Xám sáng" },
        ],
      },
    ],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "34'' H x 58'' W x 32'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Cao su", "Vải polyester"],
      belongings: null,
    },
  },
  {
    id: "p-06",
    initialPrice: 1500000,
    title: "Tủ cạnh giường Carnforth",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "closet-cabinet",
    distributor: { name: "Phố Xinh", search: "pho-xinh" },
    tags: {
      new: false,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "22.09'' H x 15.79'' W x 16.34'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: null,
    },
  },
  {
    id: "p-07",
    initialPrice: 5000000,
    title: "Bộ tủ bếp Aaronsburg",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "closet-cabinet",
    distributor: { name: "Hòa Phát", search: "hoa-phat" },
    tags: {
      new: false,
      bestSeller: true,
      discount: 30,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "HoaPhatFreeShip",
      },
    ],
    sort: [
      {
        type: "color",
        defaultValue: "white",
        name: "Màu sắc",
        values: [
          { value: "white", name: "Trắng", default: true },
          { value: "coffee", name: "Cà phê" },
        ],
      },
    ],
    policy: [
      { warranty: { time: 1, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "72.25'' H x 29.13'' W x 15.75'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: null,
    },
  },
  {
    id: "p-08",
    initialPrice: 8800000,
    title: "Bộ tủ TV cỡ lớn Doralynn",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "closet-cabinet",
    distributor: { name: "Decox", search: "decox" },
    tags: {
      new: true,
      bestSeller: false,
      discount: false,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "DecoxFreeShip",
      },
    ],
    sort: [],
    policy: [
      { warranty: { time: 2, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "94.25'' x 72'' x 15.75''",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: null,
    },
  },
  {
    id: "p-09",
    initialPrice: 6600000,
    title: "Bộ giường Marla",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "bed",
    distributor: { name: "Chilai", search: "chilai" },
    tags: {
      new: false,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [],
    policy: [
      { warranty: { time: 2, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "62.6'' W x 82.7'' L",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Thép không gỉ"],
      belongings: "Bộ khung đỡ",
    },
  },
  {
    id: "p-10",
    initialPrice: 4700000,
    title: "Bộ 4 ghế phòng ăn Polyurethane",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "chair",
    distributor: { name: "Phố Xinh", search: "pho-xinh" },
    tags: {
      new: false,
      bestSeller: true,
      discount: 20,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "PhoXinhFreeShip",
      },
    ],
    sort: [
      {
        type: "color",
        defaultValue: "teal",
        name: "Màu sắc",
        values: [
          { value: "teal", name: "Xanh lá", default: true },
          { value: "white", name: "Trắng" },
        ],
      },
    ],
    policy: [
      { warranty: { time: 1, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "32.09'' H x 18.89'' W",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Nhựa PVC", "Cao su"],
      belongings: null,
    },
  },
  {
    id: "p-11",
    initialPrice: 6000000,
    title: "Bàn cà phê Alezzi",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "table",
    distributor: { name: "Hòa Phát", search: "hoa-phat" },
    tags: {
      new: true,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "18'' H x 42'' L x 24'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: null,
    },
  },
  {
    id: "p-12",
    initialPrice: 1800000,
    title: "Tủ cạnh giường Guilford",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "closet-cabinet",
    distributor: { name: "Decox", search: "decox" },
    tags: {
      new: false,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [
      {
        type: "color",
        defaultValue: "black",
        name: "Màu sắc",
        values: [
          { value: "black", name: "Đen", default: true },
          { value: "white", name: "Trắng" },
        ],
      },
    ],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "19.06'' H x 14.92'' W x 12.5'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: null,
    },
  },
  {
    id: "p-13",
    initialPrice: 5600000,
    title: "Tủ bếp Tressa",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "closet-cabinet",
    distributor: { name: "Chilai", search: "chi-lai" },
    tags: {
      new: false,
      bestSeller: true,
      discount: 15,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "ChilaiFreeShip",
      },
    ],
    sort: [],
    policy: [
      { warranty: { time: 1, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "35.98'' H x 35.67'' W x 16.54'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Thủy tinh"],
      belongings: null,
    },
  },
  {
    id: "p-14",
    initialPrice: 7200000,
    title: "Ghế sofa Theodore",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "chair",
    distributor: { name: "Phố Xinh", search: "pho-xinh" },
    tags: {
      new: true,
      bestSeller: false,
      discount: false,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "PhoXinhFreeShip",
      },
    ],
    sort: [
      {
        type: "color",
        defaultValue: "beige",
        name: "Màu sắc",
        values: [
          { value: "beige", name: "Be", default: true },
          { value: "blue", name: "Xanh dương" },
        ],
      },
    ],
    policy: [
      { warranty: { time: 1.5, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "36'' H x 55'' W x 30'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Vải polyester"],
      belongings: null,
    },
  },
  {
    id: "p-15",
    initialPrice: 16000000,
    title: "Tủ quần áo đa dụng Home Storage",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "closet-cabinet",
    distributor: { name: "Hòa Phát", search: "hoa-phat" },
    tags: {
      new: false,
      bestSeller: false,
      discount: false,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "HoaPhatFreeShip",
      },
    ],
    sort: [],
    policy: [
      { warranty: { time: 1.5, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "84'' H x 113'' W x 16.75'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: null,
    },
  },
  {
    id: "p-16",
    initialPrice: 4200000,
    title: "Bộ 2 ghế phòng ăn Annabelle Velvet",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "chair",
    distributor: { name: "Decox", search: "decox" },
    tags: {
      new: false,
      bestSeller: true,
      discount: 20,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [
      {
        type: "color",
        defaultValue: "rose",
        name: "Màu sắc",
        values: [
          { value: "rose", name: "Hồng", default: true },
          { value: "green", name: "Xanh lá" },
        ],
      },
    ],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "35.98'' H x 35.67'' W x 16.54'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Vải polyester", "Cao su"],
      belongings: null,
    },
  },
  {
    id: "p-17",
    initialPrice: 11000000,
    title: "Bàn cà phê Neko",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "table",
    distributor: { name: "Chilai", search: "chilai" },
    tags: {
      new: true,
      bestSeller: false,
      discount: false,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "ChilaiFreeShip",
      },
    ],
    sort: [],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "36'' H x 55'' W x 30'' D",
      madeIn: "Việt Nam",
      material: ["Thép không gỉ", "Đá granit"],
      belongings: null,
    },
  },
  {
    id: "p-18",
    initialPrice: 2000000,
    title: "Tủ cạnh giường Dillwyn",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "closet-cabinet",
    distributor: { name: "Phố Xinh", search: "pho-xinh" },
    tags: {
      new: false,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [
      {
        type: "color",
        defaultValue: "white",
        name: "Màu sắc",
        values: [
          { value: "white", name: "Trắng", default: true },
          { value: "walnut", name: "Vân gỗ" },
        ],
      },
    ],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "16.65'' H x 15.75'' W x 15.85'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp"],
      belongings: null,
    },
  },
  {
    id: "p-19",
    initialPrice: 7000000,
    title: "Bàn ăn Beaufort",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "table",
    distributor: { name: "Hòa Phát", search: "hoa-phat" },
    tags: {
      new: false,
      bestSeller: true,
      discount: false,
      freeShip: true,
      gift: false,
    },
    promotion: [
      {
        freeShipCode: "HoaPhatFreeShip",
      },
    ],
    sort: [],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "36'' L x 36'' D x 30'' H",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Thép không gỉ"],
      belongings: null,
    },
  },
  {
    id: "p-20",
    initialPrice: 4400000,
    title: "Bộ tủ TV Wodome",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "closet-cabinet",
    distributor: { name: "Decox", search: "decox" },
    tags: {
      new: true,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [
      {
        type: "color",
        defaultValue: "white",
        name: "Màu sắc",
        values: [
          { value: "white", name: "Trắng", default: true },
          { value: "Black", name: "Đen" },
        ],
      },
    ],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "17.7'' H x 13.8'' x 51.2'' x 17.7'' x 13.8''",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Thủy tinh"],
      belongings: null,
    },
  },
  {
    id: "p-21",
    initialPrice: 3600000,
    title: "Bộ giường Matheney",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "bed",
    distributor: { name: "Chilai", search: "chilai" },
    tags: {
      new: false,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [
      {
        type: "color",
        defaultValue: "black",
        name: "Màu sắc",
        values: [
          { value: "black", name: "Đen", default: true },
          { value: "gold", name: "Vàng" },
        ],
      },
    ],
    policy: [
      { warranty: { time: 2, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "16.65'' H x 15.75'' W x 15.85'' D",
      madeIn: "Việt Nam",
      material: ["Thép không gỉ"],
      belongings: "Bộ khung đỡ",
    },
  },
  {
    id: "p-22",
    initialPrice: 3200000,
    title: "Bộ 2 ghế phòng ăn Brady Velvet",
    category: { value: "kitchen", name: "Nhà bếp" },
    productType: "chair",
    distributor: { name: "Phố Xinh", search: "pho-xinh" },
    tags: {
      new: false,
      bestSeller: true,
      discount: 25,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [
      {
        type: "color",
        defaultValue: "rose",
        name: "Màu sắc",
        values: [
          { value: "rose", name: "Hồng", default: true },
          { value: "gray", name: "Xám" },
        ],
      },
    ],
    policy: [
      { warranty: null, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "31.5'' H x 20.1'' W x 21.7'' D",
      madeIn: "Việt Nam",
      material: ["Vải polyester", "Cao su", "Thép không gỉ"],
      belongings: null,
    },
  },
  {
    id: "p-23",
    initialPrice: 7200000,
    title: "Ghế sofa Abbigale",
    category: { value: "living-room", name: "Phòng khách" },
    productType: "chair",
    distributor: { name: "Hòa Phát", search: "hoa-phat" },
    tags: {
      new: true,
      bestSeller: false,
      discount: false,
      freeShip: true,
      gift: false,
    },
    promotion: [],
    sort: [
      {
        type: "color",
        defaultValue: "black",
        name: "Màu sắc",
        values: [
          { value: "black", name: "Đen", default: true },
          { value: "brown", name: "Nâu" },
        ],
      },
    ],
    policy: [
      { warranty: { time: 2, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 3, to: 5 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "23'' H x 65.8'' W x 36'' D",
      madeIn: "Việt Nam",
      material: ["Gỗ công nghiệp", "Cao su"],
      belongings: "Bộ 2 gối",
    },
  },
  {
    id: "p-24",
    initialPrice: 4200000,
    title: "Bộ giường Gerardi",
    category: { value: "bed-room", name: "Phòng ngủ" },
    productType: "bed",
    distributor: { name: "Decox", search: "decox" },
    tags: {
      new: false,
      bestSeller: false,
      discount: false,
      freeShip: false,
      gift: false,
    },
    promotion: [],
    sort: [],
    policy: [
      { warranty: { time: 2, unit: "năm" }, icon: "warranty" },
      { deliveryDate: { from: 4, to: 7 }, icon: "delivery" },
      { gift: false, icon: "gift" },
    ],
    specs: {
      size: "45'' H x 41'' W x 75'' L",
      madeIn: "Việt Nam",
      material: ["Thép không gỉ", "Gỗ công nghiệp"],
      belongings: "Bộ khung đỡ",
    },
  },
];
